version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly" # Options: "daily", "weekly", "monthly"
      day: "monday"
      time: "09:00"
    timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3